#!/usr/bin/env bash
#
# wt-init.sh — assemble a self-contained ./mkwt.sh in $PWD and register it in
# .git/info/exclude. PURELY MECHANICAL: it does not decide where the repo is or
# where worktrees go. The caller (the /wt skill / agent) passes <repo-rel>;
# the worktree location is fixed downstream as <repo>.worktrees/<slug>.
#
# Usage: wt-init.sh <repo-rel>
#   <repo-rel>  path from $PWD (where mkwt.sh is dropped) to the repo it drives.
#               "."         → $PWD is the repo root (mkwt sits at the repo root)
#               "<subdir>"  → the repo is that subfolder of $PWD (container layout)
#
# wt-init does no detection: it validates that <repo-rel> points at a repo root
# and bakes it in. Deciding <repo-rel> is the caller's job — see SKILL.md.

set -euo pipefail
die() { printf 'wt-init: %s\n' "$1" >&2; exit 1; }

[ $# -ge 1 ] || die "usage: wt-init.sh <repo-rel>   (e.g. '.' or a subfolder name)"
repo_rel="$1"
root="$PWD"
src="$(cd "$(dirname "$0")" && pwd)"

# Validate (not detect): the given repo-rel must point at a git repo root.
repo="$(cd "$root/$repo_rel" 2>/dev/null && pwd)" \
  || die "no such directory: $root/$repo_rel"
git -C "$repo" rev-parse --is-inside-work-tree >/dev/null 2>&1 \
  || die "not a git repo: $repo"
toplevel="$(cd "$(git -C "$repo" rev-parse --show-toplevel)" && pwd)"
[ "$toplevel" = "$repo" ] \
  || die "repo-rel must point at the repo root (its toplevel is $toplevel)"

out="$root/mkwt.sh"
[ -e "$out" ] && die "mkwt.sh already exists at $root — remove it first to regenerate"

[ -f "$src/wt-land.sh" ]    || die "missing template: $src/wt-land.sh"
[ -f "$src/wt-destroy.sh" ] || die "missing template: $src/wt-destroy.sh"
[ -f "$src/mkwt-body.sh" ]  || die "missing template: $src/mkwt-body.sh"

land_b64="$(base64 < "$src/wt-land.sh"    | tr -d '\n')"
destroy_b64="$(base64 < "$src/wt-destroy.sh" | tr -d '\n')"

# Assemble: shebang + baked config + static body.
{
  printf '#!/usr/bin/env bash\n'
  printf '# === generated by /wt — do not edit; re-run /wt to regenerate ===\n'
  printf 'REPO_REL=%q\n' "$repo_rel"
  printf 'WT_LAND_B64=%q\n' "$land_b64"
  printf 'WT_DESTROY_B64=%q\n' "$destroy_b64"
  cat "$src/mkwt-body.sh"
} > "$out"
chmod +x "$out"

# Hide mkwt.sh from git status when it sits inside the repo's working tree
# (drop dir == repo root). Compare resolved paths so "./." etc. also count.
if [ "$repo" = "$root" ]; then
  common_dir="$(cd "$repo" && cd "$(git rev-parse --git-common-dir)" && pwd)"
  mkdir -p "$common_dir/info"
  grep -qxF "/mkwt.sh" "$common_dir/info/exclude" 2>/dev/null \
    || printf '/mkwt.sh\n' >> "$common_dir/info/exclude"
  printf 'excluded /mkwt.sh via %s/info/exclude\n' "$common_dir" >&2
fi

printf 'dropped %s (repo-rel: %s)\n' "$out" "$repo_rel" >&2
printf 'usage: ./mkwt.sh <branch-name>   e.g. ./mkwt.sh feat/login\n' >&2
printf '  inside tmux  -> new window at the worktree, named after the branch\n' >&2
printf '  otherwise    -> prints the worktree path to cd into\n' >&2
