#!/usr/bin/env bash
#
# wt-init.sh — assemble a self-contained ./mkwt.sh in $PWD, run its `init` to
# produce a starting .wtrc, and drop the shared CLAUDE.md worktrees will inherit.
# PURELY MECHANICAL: it does not decide where the repo is, and it does not write
# the post_create hook. Both are the caller's job — the /wt skill decides the
# layout and asks the user what a new worktree should open, then edits .wtrc.
#
# Usage: wt-init.sh <repo-rel>
#   <repo-rel>  path from $PWD (where mkwt.sh is dropped) to the repo it drives.
#               "."         → $PWD is the repo root (mkwt sits at the repo root)
#               "<subdir>"  → the repo is that subfolder of $PWD (container layout)
#
# wt-init does no detection: it validates that <repo-rel> points at a repo root
# and hands it to `mkwt.sh init`. Deciding <repo-rel> is the caller's job — see
# SKILL.md.

set -euo pipefail
die() { printf 'wt-init: %s\n' "$1" >&2; exit 1; }

[ $# -ge 1 ] || die "usage: wt-init.sh <repo-rel>   (e.g. '.' or a subfolder name)"
repo_rel="$1"
root="$PWD"
src="$(cd "$(dirname "$0")" && pwd)"

# Validate (not detect): the given repo-rel must point at a git repo root.
repo="$(cd "$root/$repo_rel" 2>/dev/null && pwd)" \
  || die "no such directory: $root/$repo_rel"
git -C "$repo" rev-parse --is-inside-work-tree >/dev/null 2>&1 \
  || die "not a git repo: $repo"
toplevel="$(cd "$(git -C "$repo" rev-parse --show-toplevel)" && pwd)"
[ "$toplevel" = "$repo" ] \
  || die "repo-rel must point at the repo root (its toplevel is $toplevel)"

out="$root/mkwt.sh"
[ -e "$out" ] && die "mkwt.sh already exists at $root — remove it first to regenerate"

[ -f "$src/wt.sh" ]              || die "missing template: $src/wt.sh"
[ -f "$src/mkwt-body.sh" ]       || die "missing template: $src/mkwt-body.sh"
[ -f "$src/worktree-claude.md" ] || die "missing template: $src/worktree-claude.md"

wt_b64="$(base64 < "$src/wt.sh" | tr -d '\n')"

# Assemble: shebang + payload + static body. The payload is the only baked value
# left; everything configurable now lives in .wtrc, which `init` writes below.
{
  printf '#!/usr/bin/env bash\n'
  printf '# === generated by /wt — do not edit; re-run /wt to regenerate ===\n'
  printf '# Configuration is NOT in here: see .wtrc next to this file.\n'
  printf 'WT_B64=%q\n' "$wt_b64"
  cat "$src/mkwt-body.sh"
} > "$out"
chmod +x "$out"

# mkwt owns .wtrc and the exclude entries, so setup goes through its own `init`
# rather than being duplicated here. It keeps an existing .wtrc untouched.
"$out" init "$repo_rel" || die "mkwt.sh init failed"

# Read back where mkwt will actually put worktrees, rather than recomputing the
# path here — two copies of that rule is how they drift.
worktree_dir=""
# shellcheck disable=SC1091
. "$root/.wtrc"
[ -n "$worktree_dir" ] || die "mkwt.sh init left worktree_dir empty in $root/.wtrc"
case "$worktree_dir" in
  /*) group_dir="$worktree_dir" ;;
  *)  group_dir="$root/$worktree_dir" ;;
esac

# Drop a shared CLAUDE.md into the worktree folder so every worktree picks it up
# as a parent-directory instruction file. Created once and never clobbered (it
# may carry the user's edits). The folder persists across `wt destroy` because
# its rmdir only removes it while empty.
mkdir -p "$group_dir"
if [ -e "$group_dir/CLAUDE.md" ]; then
  printf 'kept existing %s\n' "$group_dir/CLAUDE.md" >&2
else
  cp "$src/worktree-claude.md" "$group_dir/CLAUDE.md" \
    || die "could not write $group_dir/CLAUDE.md"
  printf 'dropped %s\n' "$group_dir/CLAUDE.md" >&2
fi

printf 'dropped %s (repo-rel: %s)\n' "$out" "$repo_rel" >&2
printf 'usage: ./mkwt.sh <branch-name>   e.g. ./mkwt.sh feat/login\n' >&2
printf 'next:  add a post_create hook to %s/.wtrc if a new worktree should open something\n' "$root" >&2
